# Generated by Django 4.1 on 2022-08-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='title',
        ),
    ]
