# Generated by Django 4.1 on 2022-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ManyToManyField(to='store_api.product'),
        ),
    ]
