# Generated by Django 4.1 on 2022-08-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
